version: "3.3"
services:
  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
        - ./sources:/var/www/metagol
        - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - frontend 
      - backend
  php:
    build: ./docker/php
    volumes:
        - ./sources:/var/www/metagol
        - ./metagol:/srv/metagol
    networks:
      - backend
  db:
    image: mariadb
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: metagol
      MYSQL_DATABASE: metagolDB
      MYSQL_USER: metagol
      MYSQL_PASSWORD: metagol
    networks:
      - backend
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8181:80"
    environment:
      PMA_HOST: db
    networks:
      - frontend 
      - backend

networks:
  frontend:
  backend:

volumes:
  db-data: